// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ProfileInfo {
    "name": string;
    "address": string;
    "endpoint": string;
    "account_id": string;
    "warp_plus": boolean;

    /** Creates a new ProfileInfo instance. */
    constructor($$source: Partial<ProfileInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("address" in $$source)) {
            this["address"] = "";
        }
        if (!("endpoint" in $$source)) {
            this["endpoint"] = "";
        }
        if (!("account_id" in $$source)) {
            this["account_id"] = "";
        }
        if (!("warp_plus" in $$source)) {
            this["warp_plus"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProfileInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ProfileInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProfileInfo($$parsedSource as Partial<ProfileInfo>);
    }
}
