// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as vpn$0 from "./internal/vpn/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Connect(profileName: string): $CancellablePromise<void> {
    return $Call.ByID(1349644773, profileName);
}

export function DeleteProfile(name: string): $CancellablePromise<void> {
    return $Call.ByID(945465803, name);
}

export function Disconnect(): $CancellablePromise<void> {
    return $Call.ByID(3318276551);
}

export function GetProfile(name: string): $CancellablePromise<$models.ProfileInfo | null> {
    return $Call.ByID(364720588, name).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetStatus(): $CancellablePromise<vpn$0.VpnStatus | null> {
    return $Call.ByID(147336629).then(($result: any) => {
        return $$createType3($result);
    });
}

export function ListProfiles(): $CancellablePromise<($models.ProfileInfo | null)[]> {
    return $Call.ByID(1983022287).then(($result: any) => {
        return $$createType4($result);
    });
}

export function Register(profileName: string, license: string): $CancellablePromise<$models.ProfileInfo | null> {
    return $Call.ByID(1333602940, profileName, license).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.ProfileInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = vpn$0.VpnStatus.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Array($$createType1);
