# -*- coding: utf-8 -*-
"""
Pre-flight check shared by all tests that depend on the local `zapret/`
working tree. The tree is generated by `tools\setup.bat` (downloads
binaries, lists, .bat strategy files from 4 upstream sources).

Why this exists:
    The `zapret/` directory is large and is .gitignored, so a fresh
    checkout / accidental deletion leaves tests with cryptic "0 files"
    failures. This helper detects the missing tree and either:
      - prints a clear, actionable warning (default), or
      - re-runs `tools\setup.bat` automatically when the env var
        `VPNCLIENT_AUTO_SETUP=1` is set.
"""
import os
import sys
import shutil
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ZAPRET_DIR = ROOT / "zapret"


def required_paths() -> list[tuple[str, Path]]:
    """Return (label, absolute_path) for every file/dir we need for tests."""
    return [
        ("zapret/                 (strategy .bat files)", ZAPRET_DIR),
        ("zapret/zapret2/         (v2 strategy .bat files)", ZAPRET_DIR / "zapret2"),
        ("zapret/bin/             (v1 binaries)", ZAPRET_DIR / "bin"),
        ("zapret/bin/winws.exe    (v1 winws)", ZAPRET_DIR / "bin" / "winws.exe"),
        ("zapret/bin/WinDivert.dll (Flowseal 47616 bytes)",
         ZAPRET_DIR / "bin" / "WinDivert.dll"),
        ("zapret/bin/WinDivert64.sys (kernel driver)",
         ZAPRET_DIR / "bin" / "WinDivert64.sys"),
        ("zapret/lists/           (v1 list files)", ZAPRET_DIR / "lists"),
        ("zapret/zapret2/bin/winws2.exe (v2 winws)",
         ZAPRET_DIR / "zapret2" / "bin" / "winws2.exe"),
    ]


def check_setup(verbose: bool = True) -> tuple[bool, list[str]]:
    """Return (ok, missing_labels).

    If `VPNCLIENT_AUTO_SETUP=1` is set and the tree is missing, this
    will run `tools\\setup.bat` and re-check afterwards.
    """
    missing: list[str] = []
    for label, p in required_paths():
        if not p.exists():
            missing.append(label)

    if not missing:
        if verbose:
            print(f"  [preflight] zapret tree present at {ZAPRET_DIR}")
        return True, []

    if os.environ.get("VPNCLIENT_AUTO_SETUP") == "1":
        print(f"  [preflight] zapret tree missing ({len(missing)} items).")
        print(f"  [preflight] VPNCLIENT_AUTO_SETUP=1 -> running tools\\setup.bat ...")
        setup_bat = ROOT / "tools" / "setup.bat"
        if not setup_bat.exists():
            print(f"  [preflight] ERROR: {setup_bat} not found")
            return False, missing
        # Stream the output so the user sees progress.
        rc = subprocess.call(
            ["cmd.exe", "/c", str(setup_bat)],
            cwd=str(ROOT),
        )
        if rc != 0:
            print(f"  [preflight] setup.bat exited with {rc}")
            return False, missing
        # Re-check after setup.
        missing = [label for label, p in required_paths() if not p.exists()]
        if not missing:
            print(f"  [preflight] setup.bat restored the tree.")
            return True, []
        print(f"  [preflight] setup.bat ran but {len(missing)} items still missing.")

    if verbose:
        print()
        print("  " + "=" * 68)
        print("  PRE-FLIGHT: zapret/ working tree is missing!")
        print("  " + "=" * 68)
        print("  The tests below need the local zapret/ folder (with binaries,")
        print("  .bat strategy files, and lists). It's generated by setup.bat.")
        print()
        print("  Missing items:")
        for m in missing:
            print(f"    - {m}")
        print()
        print("  How to fix:")
        print("    1. Run setup once:        tools\\setup.bat")
        print("    2. Or auto-restore:       set VPNCLIENT_AUTO_SETUP=1")
        print("                              python tests/test_zapret_selection.py")
        print()
        print("  Setup pulls binaries from:")
        print("    - youtubediscord/zapret     (winws.exe v1+v2, .bin, .txt)")
        print("    - Flowseal/zapret-discord-youtube  (WinDivert.dll 47616 b)")
        print("    - pumPCin/AntiZapret        (list-extended.txt)")
        print("    - bol-van/zapret            (lua scripts)")
        print("    - bol-van/zapret-win-bundle (lua scripts)")
        print()
    return False, missing


if __name__ == "__main__":
    """Standalone: print a status report and exit 0 (ok) / 1 (missing)."""
    ok, missing = check_setup(verbose=True)
    sys.exit(0 if ok else 1)
