// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class VpnStatus {
    "connected": boolean;
    "profile": string;
    "address": string;
    "endpoint": string;
    "tx_bytes": number;
    "rx_bytes": number;
    "uptime": string;

    /** Creates a new VpnStatus instance. */
    constructor($$source: Partial<VpnStatus> = {}) {
        if (!("connected" in $$source)) {
            this["connected"] = false;
        }
        if (!("profile" in $$source)) {
            this["profile"] = "";
        }
        if (!("address" in $$source)) {
            this["address"] = "";
        }
        if (!("endpoint" in $$source)) {
            this["endpoint"] = "";
        }
        if (!("tx_bytes" in $$source)) {
            this["tx_bytes"] = 0;
        }
        if (!("rx_bytes" in $$source)) {
            this["rx_bytes"] = 0;
        }
        if (!("uptime" in $$source)) {
            this["uptime"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VpnStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): VpnStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VpnStatus($$parsedSource as Partial<VpnStatus>);
    }
}
